create_config() {
  mkdir -p /boot/extlinux
  echo "LABEL Orangepi OS
LINUX /Image
INITRD /initramfs-linux.img
FDT /dtbs/rockchip/rk3588s-orangepi-5.dtb
APPEND earlyprintk console=tty1 consoleblank=0 rw rootwait root=/dev/mmcblk1p2  audit=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M" \
    > /boot/extlinux/extlinux.conf
}

post_install() {
  create_config
}
